version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
    working_directory: ~/my_app
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          pip install awscli --upgrade --user;
          export PATH=$PATH:~/.local/bin;
          eval $(aws ecr get-login --region us-east-2 --no-include-email);
          docker build -t 866624549710.dkr.ecr.us-east-2.amazonaws.com/nginx:latest .;
          docker push 866624549710.dkr.ecr.us-east-2.amazonaws.com/nginx:latest
